import { assertHookContextFits } from '../instructions.js';

/**
 * Pure generators for the Codex CLI per-session configuration.
 *
 * Codex is configured via `-c key=value` CLI overrides (values parse as TOML),
 * so identity wiring never touches `~/.codex/config.toml` or CODEX_HOME —
 * auth stays wherever the operator set it up.
 *
 * Verified against the Codex CLI docs (mid-2026):
 * - MCP streamable HTTP servers: `mcp_servers.<id>.url` / `tool_timeout_sec`
 *   (https://developers.openai.com/codex/config-reference, /codex/mcp)
 * - notify: array<string> command; Codex appends the event JSON as the final
 *   argv argument (https://developers.openai.com/codex/config-reference)
 * - lifecycle hooks and hook payloads (https://developers.openai.com/codex/hooks)
 * - approvals/sandbox: `approval_policy` / `sandbox_mode` config keys and the
 *   `--dangerously-bypass-approvals-and-sandbox` flag
 *   (https://developers.openai.com/codex/cli/reference)
 * - reasoning effort: `model_reasoning_effort`
 *   (https://developers.openai.com/codex/config-reference)
 */

/** Marker stamped into every file we generate so prepare() never clobbers a human-authored file. */
export const GENERATED_MARKER = 'generated by agent-conductor (codex runtime)';

const CONDUCTOR_BLOCK_START = `<!-- ${GENERATED_MARKER}: instructions begin -->`;
const CONDUCTOR_BLOCK_END = `<!-- ${GENERATED_MARKER}: instructions end -->`;
const GENERATED_FILE_MARKER = `<!-- ${GENERATED_MARKER}; do not edit or commit — regenerated on every prepare() -->`;

/** Space reserved for repository and nested AGENTS files after the home override. */
export const REPOSITORY_DOC_BUDGET_BYTES = 32 * 1024;
/** Slack for Codex-generated framing and modest repository growth. */
export const PROJECT_DOC_HEADROOM_BYTES = 8 * 1024;
/** A global file above this size is shortened before mandatory managed instructions are appended. */
export const MAX_INHERITED_GUIDANCE_BYTES = 64 * 1024;

/** Name of the conductor's MCP server entry in the session's Codex config. */
export const MCP_SERVER_NAME = 'conductor';

export interface CodexOverrideOptions {
  /** Per-session MCP URL — the mechanical identity. */
  mcpUrl: string;
  /** The notify command Codex invokes with the event JSON appended as the last argv element. */
  notifyCommand: readonly string[];
  /** Per-tool timeout for conductor MCP calls (Codex default is 60s — too low for long consults). */
  toolTimeoutSec: number;
  /** Run without approval prompts or sandbox restrictions. */
  bypassPermissions: boolean;
  /** Runtime-specific reasoning effort passed through to model_reasoning_effort. */
  effort?: string;
  /** Strip UI chrome and non-essential traffic (update check, analytics, tips, animations, title writes). */
  bareUi: boolean;
}

/** Escape a string for use as a TOML basic (double-quoted) string. */
export function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

/** Quote a string for POSIX shells (single-quote, with embedded quotes escaped). */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * The `-c key=value` override strings for one session launch.
 * Each entry is a raw `key=value` pair; callers shell-quote them.
 */
export function buildConfigOverrides(opts: CodexOverrideOptions): string[] {
  const notifyArray = `[${opts.notifyCommand.map(tomlString).join(',')}]`;
  const overrides = [
    `mcp_servers.${MCP_SERVER_NAME}.url=${tomlString(opts.mcpUrl)}`,
    `mcp_servers.${MCP_SERVER_NAME}.tool_timeout_sec=${opts.toolTimeoutSec}`,
    `notify=${notifyArray}`,
    // Codex's paste-burst heuristic swallows the Enter the conductor sends
    // right after a bracketed paste, leaving delivered messages sitting
    // UNSUBMITTED in the composer (verified against 0.144.3). Multiline safety
    // still rides on bracketed-paste markers; only the timing heuristic goes.
    `disable_paste_burst=true`,
    // NOTE: folder trust cannot ride on -c overrides — Codex only honors
    // trust from the config FILE. prepareCodexHome() appends the trust entry
    // to the per-session config.toml copy instead.
  ];
  if (opts.effort !== undefined) overrides.push(`model_reasoning_effort=${tomlString(opts.effort)}`);
  if (opts.bypassPermissions) {
    overrides.push(
      // Belt and braces alongside --dangerously-bypass-approvals-and-sandbox:
      // `codex resume` has been observed to drop the bypass *flag* (openai/codex#9144),
      // while -c overrides apply on every invocation.
      `approval_policy="never"`,
      `sandbox_mode="danger-full-access"`,
    );
  }
  if (opts.bareUi) {
    overrides.push(
      // The update check renders a BLOCKING interactive prompt at startup
      // (verified against 0.144.3) — it would hang every spawned pane.
      'check_for_update_on_startup=false',
      'analytics.enabled=false',
      // Startup tip banner ("Tip: Our most capable model yet…").
      'tui.show_tooltips=false',
      'tui.animations=false',
      // Codex writes terminal titles by default, clobbering the conductor's
      // "codename — tag" pane titles.
      'tui.terminal_title=[]',
    );
  }
  return overrides;
}

/**
 * Notify hook script. Codex invokes `notify` with the event JSON appended as
 * the final argv argument, so inside the script it arrives as `$1`.
 */
export function renderNotifyScript(eventsUrl: string): string {
  return [
    '#!/bin/sh',
    `# ${GENERATED_MARKER}; do not edit — regenerated on every prepare().`,
    '# Codex appends the notification JSON as the final argument.',
    'payload="$1"',
    '[ -n "$payload" ] || exit 0',
    `curl -fsS -m 5 -X POST -H 'Content-Type: application/json' --data "$payload" ${shellQuote(eventsUrl)} >/dev/null 2>&1 || exit 0`,
    '',
  ].join('\n');
}

const hookRelayProgram = (eventsUrl: string, maxSeconds = 4): string => `
let hookInput = '';
for await (const chunk of process.stdin) hookInput += chunk;
try {
  execFileSync('curl', ['-fsS', '-m', ${JSON.stringify(String(maxSeconds))}, '-X', 'POST', '-H', 'Content-Type: application/json', '--data-binary', '@-', ${JSON.stringify(eventsUrl)}], {
    input: hookInput,
    stdio: ['pipe', 'ignore', 'ignore'],
  });
} catch {
  // Lifecycle reporting is best-effort and must never break the Codex turn.
}
`;

/** Relay supported Codex lifecycle-hook input to the session's mechanical events endpoint. */
export function renderLifecycleHookScript(eventsUrl: string): string {
  return [
    '#!/usr/bin/env node',
    "import { execFileSync } from 'node:child_process';",
    `// ${GENERATED_MARKER}; do not edit — regenerated on every prepare().`,
    hookRelayProgram(eventsUrl).trim(),
    '',
  ].join('\n');
}

/** Model-visible reminder injected by the generated SessionStart(source=compact) hook. */
export function renderProtocolReminderScript(protocolText: string, sessionPromptText?: string | null): string {
  const labelledLayers = [
    '# Conductor protocol',
    protocolText,
    ...(sessionPromptText === undefined || sessionPromptText === null
      ? []
      : ['# Session instructions', sessionPromptText]),
  ].join('\n');
  const additionalContext = `Agent Conductor instructions restored after context compaction.\n\n${labelledLayers}`;
  assertHookContextFits(additionalContext);
  const output = {
    hookSpecificOutput: {
      hookEventName: 'SessionStart',
      additionalContext,
    },
  };
  return [
    '#!/usr/bin/env node',
    `// ${GENERATED_MARKER}; do not edit — regenerated on every prepare().`,
    `process.stdout.write(${JSON.stringify(JSON.stringify(output))});`,
    '',
  ].join('\n');
}

/** User-level hook config inside the isolated CODEX_HOME. */
export function renderProtocolHooks(reminderCommand: string, lifecycleCommand?: string): string {
  return `${JSON.stringify(
    {
      description: 'Agent Conductor managed protocol persistence.',
      hooks: {
        ...(lifecycleCommand === undefined
          ? {}
          : {
              UserPromptSubmit: [
                {
                  hooks: [{ type: 'command', command: lifecycleCommand, timeout: 5 }],
                },
              ],
              PreCompact: [
                {
                  hooks: [{ type: 'command', command: lifecycleCommand, timeout: 5 }],
                },
              ],
            }),
        SessionStart: [
          {
            matcher: '^compact$',
            hooks: [
              {
                type: 'command',
                command: reminderCommand,
                timeout: 5,
                statusMessage: 'Restoring Conductor instructions',
              },
              ...(lifecycleCommand === undefined ? [] : [{ type: 'command', command: lifecycleCommand, timeout: 5 }]),
            ],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}

/** The refreshable conductor-owned section appended to AGENTS.override.md. */
function renderConductorBlock(protocolText: string, sessionPromptText?: string | null): string {
  let content = `${CONDUCTOR_BLOCK_START}\n\n# Conductor protocol\n\n${protocolText}`;
  if (!content.endsWith('\n')) content += '\n';
  if (sessionPromptText !== undefined && sessionPromptText !== null) {
    content += `\n# Session instructions\n\n${sessionPromptText}`;
    if (!content.endsWith('\n')) content += '\n';
  }
  return `${content}\n${CONDUCTOR_BLOCK_END}`;
}

function truncateUtf8(text: string, maxBytes: number): string {
  if (Buffer.byteLength(text, 'utf8') <= maxBytes) return text;
  let bytes = 0;
  let result = '';
  for (const character of text) {
    const size = Buffer.byteLength(character, 'utf8');
    if (bytes + size > maxBytes) break;
    result += character;
    bytes += size;
  }
  return result;
}

export interface RenderHomeOverrideResult {
  content: string;
  inheritedGuidanceTruncated: boolean;
}

/**
 * Compose the always-on instruction file in a managed session's isolated
 * CODEX_HOME. Mandatory Conductor/session instructions are never candidates
 * for truncation; only inherited global guidance is bounded.
 */
export function renderHomeAgentsOverride(
  inheritedGuidance: string | null,
  protocolText: string,
  sessionPromptText?: string | null,
  maxInheritedBytes = MAX_INHERITED_GUIDANCE_BYTES,
): RenderHomeOverrideResult {
  const inherited = inheritedGuidance?.trim() ?? '';
  const shortened = truncateUtf8(inherited, maxInheritedBytes).trimEnd();
  const inheritedGuidanceTruncated = shortened !== inherited;
  const parts = [GENERATED_FILE_MARKER];
  if (shortened.length > 0) {
    parts.push('# Operator global instructions', shortened);
    if (inheritedGuidanceTruncated) {
      parts.push(
        `> Agent Conductor shortened inherited global guidance to ${maxInheritedBytes} UTF-8 bytes. ` +
          'The shared source file remains unchanged.',
      );
    }
  }
  parts.push(renderConductorBlock(protocolText, sessionPromptText));
  return { content: `${parts.join('\n\n')}\n`, inheritedGuidanceTruncated };
}

/** True only for a complete legacy file generated by Conductor, not a user file with a managed block. */
export function isGeneratedAgentsOverride(content: string): boolean {
  return content.includes(GENERATED_FILE_MARKER);
}

/**
 * Remove the legacy managed section while leaving every byte outside its
 * marker pair untouched. Unmarked and malformed files are returned unchanged.
 */
export function removeConductorInstructions(existingOverride: string): string {
  const start = existingOverride.indexOf(CONDUCTOR_BLOCK_START);
  if (start === -1) return existingOverride;
  const end = existingOverride.indexOf(CONDUCTOR_BLOCK_END, start);
  if (end === -1) return existingOverride;
  return `${existingOverride.slice(0, start)}${existingOverride.slice(end + CONDUCTOR_BLOCK_END.length)}`;
}

interface TopLevelInteger {
  value: number;
  lineIndex: number;
  prefix: string;
  suffix: string;
}

/**
 * Read one integer assignment from TOML's top-level table. This deliberately
 * stops at the first table header: a visually similar key below it belongs to
 * that table and must not be rewritten as a global Codex setting.
 */
function findTopLevelInteger(source: string, key: string): TopLevelInteger | null {
  const lines = source.split('\n');
  const assignment = new RegExp(`^(\\s*${key}\\s*=\\s*)([0-9][0-9_]*)(\\s*(?:#.*)?)$`, 'u');
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex += 1) {
    const line = lines[lineIndex] ?? '';
    const trimmed = line.trimStart();
    if (trimmed.startsWith('[')) break;
    const match = assignment.exec(line);
    if (match === null) continue;
    const raw = match[2]?.replaceAll('_', '') ?? '';
    const value = Number.parseInt(raw, 10);
    if (!Number.isSafeInteger(value)) return null;
    return { value, lineIndex, prefix: match[1] ?? '', suffix: match[3] ?? '' };
  }
  return null;
}

/** Read the effective top-level project_doc_max_bytes when it is a plain non-negative integer. */
export function readProjectDocMaxBytes(source: string): number | null {
  return findTopLevelInteger(source, 'project_doc_max_bytes')?.value ?? null;
}

/**
 * Raise project_doc_max_bytes in a generated config copy. Existing larger
 * values, comments, tables, and formatting are preserved.
 */
export function ensureProjectDocMaxBytes(source: string, minimum: number): string {
  const required = Math.max(0, Math.ceil(minimum));
  const existing = findTopLevelInteger(source, 'project_doc_max_bytes');
  if (existing !== null && existing.value >= required) return source;

  const lines = source.split('\n');
  if (existing !== null) {
    lines[existing.lineIndex] = `${existing.prefix}${required}${existing.suffix}`;
    return lines.join('\n');
  }

  const firstTable = lines.findIndex((line) => line.trimStart().startsWith('['));
  const insertAt = firstTable === -1 ? Math.max(0, lines.length - (lines.at(-1) === '' ? 1 : 0)) : firstTable;
  const generated = [`# ${GENERATED_MARKER}: protect managed instructions`, `project_doc_max_bytes = ${required}`];
  lines.splice(insertAt, 0, ...generated, '');
  return lines.join('\n');
}

/**
 * Append or refresh the conductor-owned section without replacing existing
 * AGENTS.override.md instructions. The explicit boundary comments make this
 * idempotent while preserving content outside the managed section.
 */
export function appendConductorInstructions(
  existingOverride: string,
  protocolText: string,
  sessionPromptText?: string | null,
): string {
  const block = renderConductorBlock(protocolText, sessionPromptText);
  const start = existingOverride.indexOf(CONDUCTOR_BLOCK_START);
  const end = start === -1 ? -1 : existingOverride.indexOf(CONDUCTOR_BLOCK_END, start);

  if (start !== -1 && end !== -1) {
    const before = existingOverride.slice(0, start).trimEnd();
    const after = existingOverride.slice(end + CONDUCTOR_BLOCK_END.length).trimStart();
    return `${[before, block, after].filter((part) => part.length > 0).join('\n\n')}\n`;
  }

  const existing = existingOverride.trimEnd();
  return `${existing}${existing.length > 0 ? '\n\n' : ''}${block}\n`;
}

/**
 * A new repo-root AGENTS.override.md. Codex gives this file absolute
 * precedence over AGENTS.md at the same directory level (it replaces, not
 * amends), so a generated file re-embeds the repo's own AGENTS.md before the
 * conductor section.
 */
export function renderAgentsOverride(
  protocolText: string,
  existingAgentsMd: string | null,
  sessionPromptText?: string | null,
): string {
  const parts = [GENERATED_FILE_MARKER];
  if (existingAgentsMd !== null && existingAgentsMd.trim().length > 0) {
    parts.push(existingAgentsMd.trim());
  }
  parts.push(renderConductorBlock(protocolText, sessionPromptText));
  return `${parts.join('\n\n')}\n`;
}
