/**
 * Pure generators for the Codex CLI per-session configuration.
 *
 * Codex is configured via `-c key=value` CLI overrides (values parse as TOML),
 * so identity wiring never touches `~/.codex/config.toml` or CODEX_HOME —
 * auth stays wherever the operator set it up.
 *
 * Verified against the Codex CLI docs (mid-2026):
 * - MCP streamable HTTP servers: `mcp_servers.<id>.url` / `tool_timeout_sec`
 *   (https://developers.openai.com/codex/config-reference, /codex/mcp)
 * - notify: array<string> command; Codex appends the event JSON as the final
 *   argv argument (https://developers.openai.com/codex/config-reference)
 * - approvals/sandbox: `approval_policy` / `sandbox_mode` config keys and the
 *   `--dangerously-bypass-approvals-and-sandbox` flag
 *   (https://developers.openai.com/codex/cli/reference)
 * - reasoning effort: `model_reasoning_effort`
 *   (https://developers.openai.com/codex/config-reference)
 */

/** Marker stamped into every file we generate so prepare() never clobbers a human-authored file. */
export const GENERATED_MARKER = 'generated by agent-conductor (codex runtime)';

const CONDUCTOR_BLOCK_START = `<!-- ${GENERATED_MARKER}: instructions begin -->`;
const CONDUCTOR_BLOCK_END = `<!-- ${GENERATED_MARKER}: instructions end -->`;

/** Name of the conductor's MCP server entry in the session's Codex config. */
export const MCP_SERVER_NAME = 'conductor';

export interface CodexOverrideOptions {
  /** Per-session MCP URL — the mechanical identity. */
  mcpUrl: string;
  /** The notify command Codex invokes with the event JSON appended as the last argv element. */
  notifyCommand: readonly string[];
  /** Per-tool timeout for conductor MCP calls (Codex default is 60s — too low for long consults). */
  toolTimeoutSec: number;
  /** Run without approval prompts or sandbox restrictions. */
  bypassPermissions: boolean;
  /** Runtime-specific reasoning effort passed through to model_reasoning_effort. */
  effort?: string;
  /** Strip UI chrome and non-essential traffic (update check, analytics, tips, animations, title writes). */
  bareUi: boolean;
}

/** Escape a string for use as a TOML basic (double-quoted) string. */
export function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

/** Quote a string for POSIX shells (single-quote, with embedded quotes escaped). */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * The `-c key=value` override strings for one session launch.
 * Each entry is a raw `key=value` pair; callers shell-quote them.
 */
export function buildConfigOverrides(opts: CodexOverrideOptions): string[] {
  const notifyArray = `[${opts.notifyCommand.map(tomlString).join(',')}]`;
  const overrides = [
    `mcp_servers.${MCP_SERVER_NAME}.url=${tomlString(opts.mcpUrl)}`,
    `mcp_servers.${MCP_SERVER_NAME}.tool_timeout_sec=${opts.toolTimeoutSec}`,
    `notify=${notifyArray}`,
    // Codex's paste-burst heuristic swallows the Enter the conductor sends
    // right after a bracketed paste, leaving delivered messages sitting
    // UNSUBMITTED in the composer (verified against 0.144.3). Multiline safety
    // still rides on bracketed-paste markers; only the timing heuristic goes.
    `disable_paste_burst=true`,
    // NOTE: folder trust cannot ride on -c overrides — Codex only honors
    // trust from the config FILE. prepareCodexHome() appends the trust entry
    // to the per-session config.toml copy instead.
  ];
  if (opts.effort !== undefined) overrides.push(`model_reasoning_effort=${tomlString(opts.effort)}`);
  if (opts.bypassPermissions) {
    overrides.push(
      // Belt and braces alongside --dangerously-bypass-approvals-and-sandbox:
      // `codex resume` has been observed to drop the bypass *flag* (openai/codex#9144),
      // while -c overrides apply on every invocation.
      `approval_policy="never"`,
      `sandbox_mode="danger-full-access"`,
    );
  }
  if (opts.bareUi) {
    overrides.push(
      // The update check renders a BLOCKING interactive prompt at startup
      // (verified against 0.144.3) — it would hang every spawned pane.
      'check_for_update_on_startup=false',
      'analytics.enabled=false',
      // Startup tip banner ("Tip: Our most capable model yet…").
      'tui.show_tooltips=false',
      'tui.animations=false',
      // Codex writes terminal titles by default, clobbering the conductor's
      // "codename — tag" pane titles.
      'tui.terminal_title=[]',
    );
  }
  return overrides;
}

/**
 * Notify hook script. Codex invokes `notify` with the event JSON appended as
 * the final argv argument, so inside the script it arrives as `$1`.
 */
export function renderNotifyScript(eventsUrl: string): string {
  return [
    '#!/bin/sh',
    `# ${GENERATED_MARKER}; do not edit — regenerated on every prepare().`,
    '# Codex appends the notification JSON as the final argument.',
    'payload="$1"',
    '[ -n "$payload" ] || exit 0',
    `curl -fsS -m 5 -X POST -H 'Content-Type: application/json' --data "$payload" ${shellQuote(eventsUrl)} >/dev/null 2>&1 || exit 0`,
    '',
  ].join('\n');
}

/** The refreshable conductor-owned section appended to AGENTS.override.md. */
function renderConductorBlock(protocolText: string, sessionPromptText?: string | null): string {
  const parts = [CONDUCTOR_BLOCK_START, '# Conductor protocol', protocolText.trim()];
  if (sessionPromptText !== undefined && sessionPromptText !== null && sessionPromptText.trim().length > 0) {
    parts.push('# Session instructions', sessionPromptText.trim());
  }
  parts.push(CONDUCTOR_BLOCK_END);
  return parts.join('\n\n');
}

/**
 * Append or refresh the conductor-owned section without replacing existing
 * AGENTS.override.md instructions. The explicit boundary comments make this
 * idempotent while preserving content outside the managed section.
 */
export function appendConductorInstructions(
  existingOverride: string,
  protocolText: string,
  sessionPromptText?: string | null,
): string {
  const block = renderConductorBlock(protocolText, sessionPromptText);
  const start = existingOverride.indexOf(CONDUCTOR_BLOCK_START);
  const end = start === -1 ? -1 : existingOverride.indexOf(CONDUCTOR_BLOCK_END, start);

  if (start !== -1 && end !== -1) {
    const before = existingOverride.slice(0, start).trimEnd();
    const after = existingOverride.slice(end + CONDUCTOR_BLOCK_END.length).trimStart();
    return `${[before, block, after].filter((part) => part.length > 0).join('\n\n')}\n`;
  }

  const existing = existingOverride.trimEnd();
  return `${existing}${existing.length > 0 ? '\n\n' : ''}${block}\n`;
}

/**
 * A new repo-root AGENTS.override.md. Codex gives this file absolute
 * precedence over AGENTS.md at the same directory level (it replaces, not
 * amends), so a generated file re-embeds the repo's own AGENTS.md before the
 * conductor section.
 */
export function renderAgentsOverride(
  protocolText: string,
  existingAgentsMd: string | null,
  sessionPromptText?: string | null,
): string {
  const parts = [`<!-- ${GENERATED_MARKER}; do not edit or commit — regenerated on every prepare() -->`];
  if (existingAgentsMd !== null && existingAgentsMd.trim().length > 0) {
    parts.push(existingAgentsMd.trim());
  }
  parts.push(renderConductorBlock(protocolText, sessionPromptText));
  return `${parts.join('\n\n')}\n`;
}
